version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: edp_api
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    volumes:
      - edp_api:/var/lib/postgresql/data
  
volumes:
  edp_api:
